-- 코드를 입력하세요
WITH OFFLINE_SALE AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS S
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID 
    )
SELECT P.PRODUCT_CODE, P.PRICE*O.S AS SALES
    FROM PRODUCT P, OFFLINE_SALE O
    WHERE P.PRODUCT_ID = O.PRODUCT_ID
    ORDER BY SALES DESC, PRODUCT_CODE ASC