-- 코드를 입력하세요
WITH HISTORY AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    GROUP BY CAR_ID
    HAVING DATE_FORMAT(MAX(END_DATE), "%Y-%m-%d") < "2022-11-01"
    ),
    PLAN AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = "30일 이상"
    )


SELECT H.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
    FROM HISTORY H, CAR_RENTAL_COMPANY_CAR C, PLAN P
    WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = P.CAR_TYPE
    AND C.CAR_TYPE IN ("세단", "SUV")
    AND C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100 >= 500000 
    AND C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100 < 2000000
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;