-- 코드를 작성해주세요
WITH RECURSIVE NEW AS (
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION
    
    SELECT E.ID, N.PARENT_ID, N.GENERATION + 1 GENERATION
    FROM ECOLI_DATA E
    JOIN NEW N ON E.PARENT_ID = N.ID
    )
    
SELECT COUNT(*) COUNT, GENERATION
    FROM NEW N
    LEFT OUTER JOIN ECOLI_DATA E ON N.ID = E.PARENT_ID
    WHERE E.PARENT_ID IS NULL
    GROUP BY GENERATION
    ORDER BY GENERATION ASC
    