-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT*P.PRICE) AS TOTAL_SALES
    FROM FOOD_ORDER O, FOOD_PRODUCT P
    WHERE O.PRODUCT_ID = P.PRODUCT_ID AND DATE_FORMAT(O.PRODUCE_DATE, "%Y-%m") = "2022-05"
    GROUP BY PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
    