-- 코드를 입력하세요
WITH NEW AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR)
SELECT F.FLAVOR
    FROM FIRST_HALF F
    JOIN NEW N ON F.FLAVOR = N.FLAVOR
    ORDER BY F.TOTAL_ORDER + N.TOTAL_ORDER DESC
    LIMIT 3;