-- 코드를 입력하세요
WITH MAX_REVIEW AS(
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM MEMBER_PROFILE M, REST_REVIEW R, MAX_REVIEW MR
    WHERE M.MEMBER_ID = R.MEMBER_ID AND R.MEMBER_ID = MR.MEMBER_ID
    ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;